local addonName, ns = ...

local mergeTable = ns.mergeTable

---@class LOUDeathknight
---@field RAID_FINDER table<string, table>
---@field NORMAL table<string, table>
---@field HEROIC table<string, table>
---@field MYTHIC table<string, table>

ns._Gear.LOU.DEATHKNIGHT = {
  ["RAID_FINDER"] = {
    ["HELM"] = {[95444]={225454,},},
    ["SHOULDERS"] = {[95445]={225430,},},
    ["CHEST"] = {[95446]={225490,},},
    ["GAUNTLETS"] = {[95451]={225466,},},
    ["LEGGINGS"] = {[95448]={225442,},},
  },
  ["NORMAL"] = {
    ["HELM"] = {[95422]={225449,},},
    ["SHOULDERS"] = {[95423]={225425,},},
    ["CHEST"] = {[95424]={225485,},},
    ["GAUNTLETS"] = {[95429]={225461,},},
    ["LEGGINGS"] = {[95426]={225437,},},
  },
  ["HEROIC"] = {
    ["HELM"] = {[95433]={225455,},},
    ["SHOULDERS"] = {[95434]={225431,},},
    ["CHEST"] = {[95435]={225491,},},
    ["GAUNTLETS"] = {[95440]={225467,},},
    ["LEGGINGS"] = {[95437]={225443,},},
  },
  ["MYTHIC"] = {
    ["HELM"] = {[95475]={225456,},},
    ["SHOULDERS"] = {[95476]={225432,},},
    ["CHEST"] = {[95468]={225492,},},
    ["GAUNTLETS"] = {[95473]={225468,},},
    ["LEGGINGS"] = {[95470]={225444,},},
  },
}

local RAID_FINDER_DEATHKNIGHT_GEAR = {}
mergeTable(RAID_FINDER_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["RAID_FINDER"]["HELM"])
mergeTable(RAID_FINDER_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["RAID_FINDER"]["SHOULDERS"])
mergeTable(RAID_FINDER_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["RAID_FINDER"]["CHEST"])
mergeTable(RAID_FINDER_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["RAID_FINDER"]["GAUNTLETS"])
mergeTable(RAID_FINDER_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["RAID_FINDER"]["LEGGINGS"])

local NORMAL_DEATHKNIGHT_GEAR = {}
mergeTable(NORMAL_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["NORMAL"]["HELM"])
mergeTable(NORMAL_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["NORMAL"]["SHOULDERS"])
mergeTable(NORMAL_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["NORMAL"]["CHEST"])
mergeTable(NORMAL_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["NORMAL"]["GAUNTLETS"])
mergeTable(NORMAL_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["NORMAL"]["LEGGINGS"])

local HEROIC_DEATHKNIGHT_GEAR = {}
mergeTable(HEROIC_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["HEROIC"]["HELM"])
mergeTable(HEROIC_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["HEROIC"]["SHOULDERS"])
mergeTable(HEROIC_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["HEROIC"]["CHEST"])
mergeTable(HEROIC_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["HEROIC"]["GAUNTLETS"])
mergeTable(HEROIC_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["HEROIC"]["LEGGINGS"])

local MYTHIC_DEATHKNIGHT_GEAR = {}
mergeTable(MYTHIC_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["MYTHIC"]["HELM"])
mergeTable(MYTHIC_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["MYTHIC"]["SHOULDERS"])
mergeTable(MYTHIC_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["MYTHIC"]["CHEST"])
mergeTable(MYTHIC_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["MYTHIC"]["GAUNTLETS"])
mergeTable(MYTHIC_DEATHKNIGHT_GEAR, ns._Gear.LOU.DEATHKNIGHT["MYTHIC"]["LEGGINGS"])

ns._Gear.LOU["DEATHKNIGHT"]["RAID_FINDER"]["ALL"] = RAID_FINDER_DEATHKNIGHT_GEAR
ns._Gear.LOU["DEATHKNIGHT"]["NORMAL"]["ALL"] = NORMAL_DEATHKNIGHT_GEAR
ns._Gear.LOU["DEATHKNIGHT"]["HEROIC"]["ALL"] = HEROIC_DEATHKNIGHT_GEAR
ns._Gear.LOU["DEATHKNIGHT"]["MYTHIC"]["ALL"] = MYTHIC_DEATHKNIGHT_GEAR
