local addonName, ns = ...

local mergeTable = ns.mergeTable

---@class LOUDemonhunter
---@field RAID_FINDER table<string, table>
---@field NORMAL table<string, table>
---@field HEROIC table<string, table>
---@field MYTHIC table<string, table>

ns._Gear.LOU.DEMONHUNTER = {
  ["RAID_FINDER"] = {
    ["HELM"] = {[95498]={226198,},},
    ["SHOULDERS"] = {[95499]={226174,},},
    ["CHEST"] = {[95500]={226234,},},
    ["GAUNTLETS"] = {[95505]={226210,},},
    ["LEGGINGS"] = {[95502]={226186,},},
  },
  ["NORMAL"] = {
    ["HELM"] = {[95508]={226193,},},
    ["SHOULDERS"] = {[95509]={226169,},},
    ["CHEST"] = {[95510]={226229,},},
    ["GAUNTLETS"] = {[95515]={226205,},},
    ["LEGGINGS"] = {[95512]={226181,},},
  },
  ["HEROIC"] = {
    ["HELM"] = {[95488]={226199,},},
    ["SHOULDERS"] = {[95489]={226175,},},
    ["CHEST"] = {[95490]={226235,},},
    ["GAUNTLETS"] = {[95495]={226211,},},
    ["LEGGINGS"] = {[95492]={226187,},},
  },
  ["MYTHIC"] = {
    ["HELM"] = {[95536]={226200,},},
    ["SHOULDERS"] = {[95537]={226176,},},
    ["CHEST"] = {[95588]={226236,},},
    ["GAUNTLETS"] = {[95594]={226212,},},
    ["LEGGINGS"] = {[95600]={226188,},},
  },
}

local RAID_FINDER_DEMONHUNTER_GEAR = {}
mergeTable(RAID_FINDER_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["RAID_FINDER"]["HELM"])
mergeTable(RAID_FINDER_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["RAID_FINDER"]["SHOULDERS"])
mergeTable(RAID_FINDER_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["RAID_FINDER"]["CHEST"])
mergeTable(RAID_FINDER_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["RAID_FINDER"]["GAUNTLETS"])
mergeTable(RAID_FINDER_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["RAID_FINDER"]["LEGGINGS"])

local NORMAL_DEMONHUNTER_GEAR = {}
mergeTable(NORMAL_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["NORMAL"]["HELM"])
mergeTable(NORMAL_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["NORMAL"]["SHOULDERS"])
mergeTable(NORMAL_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["NORMAL"]["CHEST"])
mergeTable(NORMAL_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["NORMAL"]["GAUNTLETS"])
mergeTable(NORMAL_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["NORMAL"]["LEGGINGS"])

local HEROIC_DEMONHUNTER_GEAR = {}
mergeTable(HEROIC_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["HEROIC"]["HELM"])
mergeTable(HEROIC_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["HEROIC"]["SHOULDERS"])
mergeTable(HEROIC_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["HEROIC"]["CHEST"])
mergeTable(HEROIC_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["HEROIC"]["GAUNTLETS"])
mergeTable(HEROIC_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["HEROIC"]["LEGGINGS"])

local MYTHIC_DEMONHUNTER_GEAR = {}
mergeTable(MYTHIC_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["MYTHIC"]["HELM"])
mergeTable(MYTHIC_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["MYTHIC"]["SHOULDERS"])
mergeTable(MYTHIC_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["MYTHIC"]["CHEST"])
mergeTable(MYTHIC_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["MYTHIC"]["GAUNTLETS"])
mergeTable(MYTHIC_DEMONHUNTER_GEAR, ns._Gear.LOU.DEMONHUNTER["MYTHIC"]["LEGGINGS"])

ns._Gear.LOU["DEMONHUNTER"]["RAID_FINDER"]["ALL"] = RAID_FINDER_DEMONHUNTER_GEAR
ns._Gear.LOU["DEMONHUNTER"]["NORMAL"]["ALL"] = NORMAL_DEMONHUNTER_GEAR
ns._Gear.LOU["DEMONHUNTER"]["HEROIC"]["ALL"] = HEROIC_DEMONHUNTER_GEAR
ns._Gear.LOU["DEMONHUNTER"]["MYTHIC"]["ALL"] = MYTHIC_DEMONHUNTER_GEAR
